### ISSUE TITLE
Request: read from stdin, create single-file gist

### ISSUE THREAD

**Issue by sparr** [mtn/mkgist#2]
This would make mkgist a drop-in replacement for xclip/gpm/pbcopy

**Comment by mtn** [comment]
Done, but it seems like `Ctrl-D` must be pressed on a newline for `read()` to detect it. So I'm open to better implementation ideas :)

**Comment by sparr** [comment]
That's perfectly normal behavior for console->stdin_as_file_handle. If you pipe another process' output to it, it should behave as expected.

**Comment by mtn** [comment]
Oh cool, that makes sense. Given the current "enter a filename" would interfere with the piping behavior, I'm going to remove that and just use a generated filename. Gist has no problems with name collisions, even for public gists, so I'm just going to always use the name "out" for gists from `stdin`.
