### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by alichtman** [mtn/mkgist#3]
Being able to install this with `pip` would be dope. Any plans to support this?

**Comment by mtn** [comment]
Yea sure, I'll let you know on this issue when it's done. :-)

**Comment by mtn** [comment]
@alichtman Done -- you should be able to `pip install mkgist`.

First time pushing to `pypi` and wow did I find the tooling aggravating. But glad to have it up :-)

**Comment by alichtman** [comment]
It's on `pypi`, however it's not pulling all the dependencies like it should. 

I had to install `pyperclip` separately for everything to work. Not a huge deal, but something you can definitely fix.

**Comment by mtn** [comment]
This should be fixed now, let me know if you run into any further problems. Thank you for the suggestion and following up! 🎈

**Comment by alichtman** [comment]
Of course, man!
